In [16]:
#Importamos los paquetes necesarios
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

In [2]:
#Lectura de los archivos necesarios
df_D0=pd.read_csv("C:/master_ugr/TFM/resultados/abrolado_D0_nom_sp_DBH_altura.csv", delimiter=";", decimal=",")
df_DD=pd.read_csv("C:/master_ugr/TFM/resultados/quejigos_demas_dens_nom_sp_DBH_altura.csv", delimiter=";", decimal=",")

In [3]:
#Optimización de los archivos
df_D0.columns=["id_visita","cod_sp","nom_sp","Altura_cm","DBH_cm"]

In [4]:
#Unión de los archivos en un dataframe
df= df_D0.merge(df_DD, how="outer")
df

     id_visita  cod_sp                nom_sp  Altura_cm  DBH_cm
0            1    7150       Quercus ilex L.      500.0   11.14
1            1    7150       Quercus ilex L.      500.0   11.14
2            1    7150       Quercus ilex L.      350.0    9.54
3            1    7150       Quercus ilex L.      600.0   16.55
4            1    7150       Quercus ilex L.      300.0    8.59
..         ...     ...                   ...        ...     ...
444         16     328  Quercus faginea Lam.      450.0    7.95
445         16     328  Quercus faginea Lam.     1000.0   24.19
446         16     328  Quercus faginea Lam.      750.0   26.10
447         16     328  Quercus faginea Lam.      900.0   21.96
448         16     328  Quercus faginea Lam.      650.0   23.23

[449 rows x 5 columns]

In [5]:
#Optimización del dataframe
df_cod_nom = df.replace({328: "Quercus faginea", 
               7150: "Quercus ilex", 
               127 :"Pinus sp", 
               2247:"Fraxinus sp", 
               6206:"Cedrus atlantica"})
df_cod_nom

     id_visita           cod_sp                nom_sp  Altura_cm  DBH_cm
0            1     Quercus ilex       Quercus ilex L.      500.0   11.14
1            1     Quercus ilex       Quercus ilex L.      500.0   11.14
2            1     Quercus ilex       Quercus ilex L.      350.0    9.54
3            1     Quercus ilex       Quercus ilex L.      600.0   16.55
4            1     Quercus ilex       Quercus ilex L.      300.0    8.59
..         ...              ...                   ...        ...     ...
444         16  Quercus faginea  Quercus faginea Lam.      450.0    7.95
445         16  Quercus faginea  Quercus faginea Lam.     1000.0   24.19
446         16  Quercus faginea  Quercus faginea Lam.      750.0   26.10
447         16  Quercus faginea  Quercus faginea Lam.      900.0   21.96
448         16  Quercus faginea  Quercus faginea Lam.      650.0   23.23

[449 rows x 5 columns]

In [6]:
df_nom=df_cod_nom.drop(["nom_sp"], axis=1)
df_nom

     id_visita           cod_sp  Altura_cm  DBH_cm
0            1     Quercus ilex      500.0   11.14
1            1     Quercus ilex      500.0   11.14
2            1     Quercus ilex      350.0    9.54
3            1     Quercus ilex      600.0   16.55
4            1     Quercus ilex      300.0    8.59
..         ...              ...        ...     ...
444         16  Quercus faginea      450.0    7.95
445         16  Quercus faginea     1000.0   24.19
446         16  Quercus faginea      750.0   26.10
447         16  Quercus faginea      900.0   21.96
448         16  Quercus faginea      650.0   23.23

[449 rows x 4 columns]

In [7]:
df_nom.columns = ["id_visita", "nombre_especie", "altura_cm", "DBH_cm"]

In [8]:
#Selección de los campos de interés
faginea = df_nom["nombre_especie"] == "Quercus faginea"
df_faginea=df_nom[faginea]
df_faginea

     id_visita   nombre_especie  altura_cm  DBH_cm
7            1  Quercus faginea      400.0   11.77
12           1  Quercus faginea      800.0   14.96
13           1  Quercus faginea      850.0   16.87
17           1  Quercus faginea      700.0   15.27
18           1  Quercus faginea      800.0   17.82
..         ...              ...        ...     ...
444         16  Quercus faginea      450.0    7.95
445         16  Quercus faginea     1000.0   24.19
446         16  Quercus faginea      750.0   26.10
447         16  Quercus faginea      900.0   21.96
448         16  Quercus faginea      650.0   23.23

[272 rows x 4 columns]

In [12]:
#Obtención del area basal (ABi) de cada individuo
df_faginea["DBH_m"] = df_faginea["DBH_cm"]/100
df_faginea

C:\Users\estre\AppData\Local\Temp/ipykernel_12880/928267719.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_faginea["DBH_m"] = df_faginea["DBH_cm"]/100

     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m
7            1  Quercus faginea      400.0   11.77  0.1177
12           1  Quercus faginea      800.0   14.96  0.1496
13           1  Quercus faginea      850.0   16.87  0.1687
17           1  Quercus faginea      700.0   15.27  0.1527
18           1  Quercus faginea      800.0   17.82  0.1782
..         ...              ...        ...     ...     ...
444         16  Quercus faginea      450.0    7.95  0.0795
445         16  Quercus faginea     1000.0   24.19  0.2419
446         16  Quercus faginea      750.0   26.10  0.2610
447         16  Quercus faginea      900.0   21.96  0.2196
448         16  Quercus faginea      650.0   23.23  0.2323

[223 rows x 5 columns]

In [13]:
df_faginea["ABi"] = ((math.pi/4)*(df_faginea["DBH_m"]**2))
df_faginea

C:\Users\estre\AppData\Local\Temp/ipykernel_12880/1481160196.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_faginea["ABi"] = ((math.pi/4)*(df_faginea["DBH_m"]**2))

     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
7            1  Quercus faginea      400.0   11.77  0.1177  0.010880
12           1  Quercus faginea      800.0   14.96  0.1496  0.017577
13           1  Quercus faginea      850.0   16.87  0.1687  0.022352
17           1  Quercus faginea      700.0   15.27  0.1527  0.018313
18           1  Quercus faginea      800.0   17.82  0.1782  0.024941
..         ...              ...        ...     ...     ...       ...
444         16  Quercus faginea      450.0    7.95  0.0795  0.004964
445         16  Quercus faginea     1000.0   24.19  0.2419  0.045958
446         16  Quercus faginea      750.0   26.10  0.2610  0.053502
447         16  Quercus faginea      900.0   21.96  0.2196  0.037875
448         16  Quercus faginea      650.0   23.23  0.2323  0.042383

[223 rows x 6 columns]

In [14]:
suma=sum(df_faginea["ABi"])
suma

6.626725406769388

In [24]:
#Obtención del AB de cada punto
visitas = range (1,17)
sum_ABi = []
for i in visitas:
    id_visita = df_faginea["id_visita"] == i
    df_id_visita = df_faginea[id_visita]
    suma=sum(df_id_visita["ABi"])
    suma_ABi= (10000*suma)/314
    sum_ABi.append(suma_ABi)
    print(df_id_visita)
    print(suma)
    print(suma_ABi)

    id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
7           1  Quercus faginea      400.0   11.77  0.1177  0.010880
12          1  Quercus faginea      800.0   14.96  0.1496  0.017577
13          1  Quercus faginea      850.0   16.87  0.1687  0.022352
17          1  Quercus faginea      700.0   15.27  0.1527  0.018313
18          1  Quercus faginea      800.0   17.82  0.1782  0.024941
21          1  Quercus faginea      400.0   14.96  0.1496  0.017577
23          1  Quercus faginea      600.0   33.74  0.3374  0.089409
25          1  Quercus faginea      305.0   11.14  0.1114  0.009747
27          1  Quercus faginea      500.0   19.73  0.1973  0.030573
32          1  Quercus faginea      450.0   15.91  0.1591  0.019881
33          1  Quercus faginea      250.0   16.87  0.1687  0.022352
34          1  Quercus faginea      300.0   15.91  0.1591  0.019881
0.30348346593364234
9.665078532918546
    id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
37          2  Quercus faginea      500.0    9.86  0.0986  0.007636
38          2  Quercus faginea      500.0    9.86  0.0986  0.007636
39          2  Quercus faginea      800.0    8.59  0.0859  0.005795
40          2  Quercus faginea      350.0   11.45  0.1145  0.010297
42          2  Quercus faginea      800.0    8.27  0.0827  0.005372
44          2  Quercus faginea     1200.0   21.64  0.2164  0.036779
46          2  Quercus faginea      600.0    8.27  0.0827  0.005372
55          2  Quercus faginea      650.0   29.92  0.2992  0.070309
56          2  Quercus faginea      450.0    9.54  0.0954  0.007148
57          2  Quercus faginea      600.0   11.45  0.1145  0.010297
58          2  Quercus faginea      600.0   11.45  0.1145  0.010297
59          2  Quercus faginea      450.0   11.45  0.1145  0.010297
60          2  Quercus faginea      600.0   15.27  0.1527  0.018313
61          2  Quercus faginea      500.0    7.95  0.0795  0.004964
62          2  Quercus faginea      900.0   11.77  0.1177  0.010880
64          2  Quercus faginea      500.0   11.77  0.1177  0.010880
65          2  Quercus faginea      600.0   14.64  0.1464  0.016833
68          2  Quercus faginea      700.0   14.96  0.1496  0.017577
69          2  Quercus faginea      550.0   10.50  0.1050  0.008659
70          2  Quercus faginea      600.0   13.05  0.1305  0.013376
71          2  Quercus faginea     1000.0   19.73  0.1973  0.030573
75          2  Quercus faginea      600.0   18.78  0.1878  0.027700
79          2  Quercus faginea      250.0    8.27  0.0827  0.005372
80          2  Quercus faginea      800.0   22.60  0.2260  0.040115
82          2  Quercus faginea     1000.0   29.92  0.2992  0.070309
83          2  Quercus faginea      900.0   13.68  0.1368  0.014698
0.4774842742780626
15.206505550256772
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
88           3  Quercus faginea      700.0  141.01  1.4101  1.561672
91           3  Quercus faginea      700.0   19.73  0.1973  0.030573
92           3  Quercus faginea     1500.0   31.83  0.3183  0.079573
97           3  Quercus faginea      700.0   13.05  0.1305  0.013376
98           3  Quercus faginea      300.0    8.91  0.0891  0.006235
99           3  Quercus faginea      600.0    8.91  0.0891  0.006235
100          3  Quercus faginea      350.0    8.59  0.0859  0.005795
101          3  Quercus faginea      450.0    9.54  0.0954  0.007148
102          3  Quercus faginea     1000.0   21.00  0.2100  0.034636
103          3  Quercus faginea      200.0    8.59  0.0859  0.005795
104          3  Quercus faginea      450.0   12.09  0.1209  0.011480
105          3  Quercus faginea      550.0   11.77  0.1177  0.010880
106          3  Quercus faginea     1000.0   14.64  0.1464  0.016833
107          3  Quercus faginea      800.0   10.50  0.1050  0.008659
112          3  Quercus faginea      800.0   15.91  0.1591  0.019881
116          3  Quercus faginea     1100.0   12.73  0.1273  0.012728
121          3  Quercus faginea      900.0   21.64  0.2164  0.036779
127          3  Quercus faginea     1000.0   15.59  0.1559  0.019089
128          3  Quercus faginea      500.0    9.23  0.0923  0.006691
129          3  Quercus faginea     1000.0   16.87  0.1687  0.022352
130          3  Quercus faginea     1600.0   48.38  0.4838  0.183832
2.1002428027447277
66.88671346320788
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
141          4  Quercus faginea     1000.0   16.87  0.1687  0.022352
142          4  Quercus faginea     1000.0   19.73  0.1973  0.030573
143          4  Quercus faginea      900.0   12.73  0.1273  0.012728
144          4  Quercus faginea      700.0   13.68  0.1368  0.014698
145          4  Quercus faginea      900.0   14.00  0.1400  0.015394
146          4  Quercus faginea     1100.0   22.60  0.2260  0.040115
148          4  Quercus faginea      900.0   13.68  0.1368  0.014698
151          4  Quercus faginea      900.0   20.37  0.2037  0.032589
152          4  Quercus faginea     1200.0   24.50  0.2450  0.047144
153          4  Quercus faginea      400.0   10.50  0.1050  0.008659
154          4  Quercus faginea      450.0    8.91  0.0891  0.006235
155          4  Quercus faginea     1100.0   18.14  0.1814  0.025844
156          4  Quercus faginea      900.0   11.45  0.1145  0.010297
157          4  Quercus faginea     1200.0   17.82  0.1782  0.024941
160          4  Quercus faginea      700.0   12.73  0.1273  0.012728
161          4  Quercus faginea     1200.0   21.00  0.2100  0.034636
162          4  Quercus faginea      700.0   18.46  0.1846  0.026764
163          4  Quercus faginea      800.0   12.09  0.1209  0.011480
164          4  Quercus faginea      600.0   11.14  0.1114  0.009747
166          4  Quercus faginea      350.0   11.77  0.1177  0.010880
167          4  Quercus faginea      700.0   13.05  0.1305  0.013376
0.4258770175982778
13.562962343894197
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
180          5  Quercus faginea      950.0   23.87  0.2387  0.044750
185          5  Quercus faginea      950.0   17.82  0.1782  0.024941
187          5  Quercus faginea      750.0   11.14  0.1114  0.009747
188          5  Quercus faginea      850.0   26.73  0.2673  0.056116
189          5  Quercus faginea     1200.0   29.92  0.2992  0.070309
196          5  Quercus faginea      800.0   10.18  0.1018  0.008139
204          5  Quercus faginea      900.0   13.68  0.1368  0.014698
205          5  Quercus faginea     1100.0   24.50  0.2450  0.047144
206          5  Quercus faginea      850.0   24.19  0.2419  0.045958
211          5  Quercus faginea     1000.0   16.55  0.1655  0.021512
212          5  Quercus faginea      750.0    7.95  0.0795  0.004964
220          5  Quercus faginea     1100.0   17.50  0.1750  0.024053
221          5  Quercus faginea      950.0   14.96  0.1496  0.017577
223          5  Quercus faginea     1000.0   22.91  0.2291  0.041223
225          5  Quercus faginea     1000.0   21.00  0.2100  0.034636
226          5  Quercus faginea     1000.0   20.05  0.2005  0.031573
228          5  Quercus faginea     1100.0   24.19  0.2419  0.045958
230          5  Quercus faginea     1150.0   17.50  0.1750  0.024053
231          5  Quercus faginea      900.0   12.73  0.1273  0.012728
232          5  Quercus faginea     1000.0   28.32  0.2832  0.062991
235          5  Quercus faginea      350.0    8.27  0.0827  0.005372
236          5  Quercus faginea      600.0   10.18  0.1018  0.008139
237          5  Quercus faginea      750.0   18.46  0.1846  0.026764
238          5  Quercus faginea      900.0   18.14  0.1814  0.025844
0.7091889532757325
22.585635454641164
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
240          6  Quercus faginea      850.0    6.04  0.0604  0.002865
275          6  Quercus faginea      600.0   16.23  0.1623  0.020688
276          6  Quercus faginea      600.0   16.23  0.1623  0.020688
278          6  Quercus faginea      750.0    9.54  0.0954  0.007148
282          6  Quercus faginea      850.0   10.82  0.1082  0.009195
284          6  Quercus faginea      650.0   10.82  0.1082  0.009195
285          6  Quercus faginea      780.0   21.96  0.2196  0.037875
287          6  Quercus faginea      950.0   15.91  0.1591  0.019881
288          6  Quercus faginea      120.0   25.78  0.2578  0.052198
290          6  Quercus faginea      700.0   14.64  0.1464  0.016833
291          6  Quercus faginea     1100.0   21.64  0.2164  0.036779
293          6  Quercus faginea      700.0   12.73  0.1273  0.012728
0.24607419813148332
7.836757902276538
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
295          7  Quercus faginea     1300.0   31.51  0.3151  0.077981
296          7  Quercus faginea      900.0   14.32  0.1432  0.016106
303          7  Quercus faginea     1050.0   19.41  0.1941  0.029590
304          7  Quercus faginea      900.0   15.91  0.1591  0.019881
305          7  Quercus faginea     1100.0   26.41  0.2641  0.054781
306          7  Quercus faginea      950.0   17.82  0.1782  0.024941
307          7  Quercus faginea      750.0   11.77  0.1177  0.010880
310          7  Quercus faginea      800.0   16.55  0.1655  0.021512
311          7  Quercus faginea      800.0   18.46  0.1846  0.026764
312          7  Quercus faginea     1000.0   25.14  0.2514  0.049639
313          7  Quercus faginea      850.0   19.41  0.1941  0.029590
315          7  Quercus faginea      800.0   10.50  0.1050  0.008659
316          7  Quercus faginea      900.0   17.18  0.1718  0.023181
319          7  Quercus faginea      850.0   14.32  0.1432  0.016106
320          7  Quercus faginea     1150.0   20.37  0.2037  0.032589
321          7  Quercus faginea     1050.0   18.78  0.1878  0.027700
322          7  Quercus faginea      550.0    9.86  0.0986  0.007636
324          7  Quercus faginea     1100.0   19.73  0.1973  0.030573
326          7  Quercus faginea     1250.0   23.55  0.2355  0.043558
327          7  Quercus faginea      700.0   12.73  0.1273  0.012728
328          7  Quercus faginea     1200.0   19.73  0.1973  0.030573
0.594966189302241
18.947967812173278
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
332          8  Quercus faginea     1050.0   26.10  0.2610  0.053502
333          8  Quercus faginea      450.0   11.14  0.1114  0.009747
339          8  Quercus faginea      750.0   19.73  0.1973  0.030573
343          8  Quercus faginea      600.0   11.45  0.1145  0.010297
344          8  Quercus faginea      400.0    8.91  0.0891  0.006235
345          8  Quercus faginea      350.0    9.86  0.0986  0.007636
346          8  Quercus faginea      800.0   18.14  0.1814  0.025844
347          8  Quercus faginea      750.0   18.14  0.1814  0.025844
348          8  Quercus faginea      700.0   16.87  0.1687  0.022352
350          8  Quercus faginea     1000.0   24.19  0.2419  0.045958
353          8  Quercus faginea      900.0   15.91  0.1591  0.019881
354          8  Quercus faginea      900.0   15.59  0.1559  0.019089
0.2769581823452938
8.82032427851254
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
356          9  Quercus faginea      700.0   27.69  0.2769  0.060219
0.06021931247505224
1.9178124992054855
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
357         10  Quercus faginea      550.0   13.68  0.1368  0.014698
358         10  Quercus faginea      600.0   23.87  0.2387  0.044750
361         10  Quercus faginea      950.0   38.83  0.3883  0.118420
362         10  Quercus faginea      550.0   14.64  0.1464  0.016833
363         10  Quercus faginea      500.0   14.00  0.1400  0.015394
0.21009540671754828
6.690936519667144
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
365         11  Quercus faginea      450.0   13.36  0.1336  0.014019
366         11  Quercus faginea      240.0    8.91  0.0891  0.006235
367         11  Quercus faginea      500.0   10.50  0.1050  0.008659
0.028912681947572683
0.9207860492857542
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
368         12  Quercus faginea      450.0    8.59  0.0859  0.005795
381         12  Quercus faginea      750.0   14.64  0.1464  0.016833
382         12  Quercus faginea      600.0    8.91  0.0891  0.006235
383         12  Quercus faginea      600.0    8.91  0.0891  0.006235
384         12  Quercus faginea      500.0    9.23  0.0923  0.006691
385         12  Quercus faginea      750.0   12.41  0.1241  0.012096
386         12  Quercus faginea      900.0   12.41  0.1241  0.012096
387         12  Quercus faginea      750.0   11.77  0.1177  0.010880
388         12  Quercus faginea      650.0   14.32  0.1432  0.016106
389         12  Quercus faginea      800.0   16.55  0.1655  0.021512
390         12  Quercus faginea      500.0    8.59  0.0859  0.005795
391         12  Quercus faginea      300.0    9.54  0.0954  0.007148
392         12  Quercus faginea      750.0   17.50  0.1750  0.024053
393         12  Quercus faginea      800.0   15.91  0.1591  0.019881
394         12  Quercus faginea      450.0    7.95  0.0795  0.004964
395         12  Quercus faginea      450.0    7.63  0.0763  0.004572
396         12  Quercus faginea      450.0    9.23  0.0923  0.006691
397         12  Quercus faginea      550.0   11.14  0.1114  0.009747
398         12  Quercus faginea      350.0    9.54  0.0954  0.007148
399         12  Quercus faginea      450.0    8.91  0.0891  0.006235
400         12  Quercus faginea      600.0   12.41  0.1241  0.012096
401         12  Quercus faginea      650.0   11.45  0.1145  0.010297
402         12  Quercus faginea      300.0    8.59  0.0859  0.005795
403         12  Quercus faginea      450.0   11.77  0.1177  0.010880
404         12  Quercus faginea      350.0    7.95  0.0795  0.004964
405         12  Quercus faginea      750.0   18.46  0.1846  0.026764
406         12  Quercus faginea      650.0   13.36  0.1336  0.014019
407         12  Quercus faginea      550.0   19.09  0.1909  0.028622
408         12  Quercus faginea       40.0    8.27  0.0827  0.005372
0.3295221639438396
10.49433643133247
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
409         13  Quercus faginea      550.0   14.96  0.1496  0.017577
413         13  Quercus faginea      500.0   14.96  0.1496  0.017577
414         13  Quercus faginea      700.0   11.77  0.1177  0.010880
415         13  Quercus faginea      550.0   12.09  0.1209  0.011480
416         13  Quercus faginea      450.0   11.45  0.1145  0.010297
417         13  Quercus faginea      350.0    9.23  0.0923  0.006691
418         13  Quercus faginea      350.0    9.23  0.0923  0.006691
419         13  Quercus faginea      500.0   10.82  0.1082  0.009195
420         13  Quercus faginea      650.0   14.32  0.1432  0.016106
421         13  Quercus faginea      700.0   12.73  0.1273  0.012728
422         13  Quercus faginea      550.0   12.73  0.1273  0.012728
423         13  Quercus faginea      450.0   10.50  0.1050  0.008659
424         13  Quercus faginea      400.0   14.96  0.1496  0.017577
425         13  Quercus faginea      400.0    8.27  0.0827  0.005372
426         13  Quercus faginea      500.0   12.41  0.1241  0.012096
427         13  Quercus faginea      350.0   11.77  0.1177  0.010880
428         13  Quercus faginea      650.0   19.09  0.1909  0.028622
0.21515564069052
6.852090467850956
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
429         14  Quercus faginea      800.0   20.37  0.2037  0.032589
430         14  Quercus faginea      800.0   21.64  0.2164  0.036779
0.06936844709639564
2.209186213261008
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
432         15  Quercus faginea      750.0   18.78  0.1878  0.027700
433         15  Quercus faginea      850.0   26.10  0.2610  0.053502
434         15  Quercus faginea      400.0    7.63  0.0763  0.004572
435         15  Quercus faginea      900.0   26.10  0.2610  0.053502
436         15  Quercus faginea      400.0    9.54  0.0954  0.007148
437         15  Quercus faginea      600.0   14.64  0.1464  0.016833
438         15  Quercus faginea      400.0    7.95  0.0795  0.004964
439         15  Quercus faginea      750.0   22.91  0.2291  0.041223
440         15  Quercus faginea      850.0   24.19  0.2419  0.045958
441         15  Quercus faginea      550.0   10.50  0.1050  0.008659
0.264062109435922
8.40962131961535
     id_visita   nombre_especie  altura_cm  DBH_cm   DBH_m       ABi
442         16  Quercus faginea     1000.0   29.60  0.2960  0.068813
443         16  Quercus faginea     1200.0   28.01  0.2801  0.061619
444         16  Quercus faginea      450.0    7.95  0.0795  0.004964
445         16  Quercus faginea     1000.0   24.19  0.2419  0.045958
446         16  Quercus faginea      750.0   26.10  0.2610  0.053502
447         16  Quercus faginea      900.0   21.96  0.2196  0.037875
448         16  Quercus faginea      650.0   23.23  0.2323  0.042383
0.315114560853083
10.035495568569523

In [23]:
sum_ABi

[9.665078532918546,
 15.206505550256772,
 66.88671346320788,
 13.562962343894197,
 22.585635454641164,
 7.836757902276538,
 18.947967812173278,
 8.82032427851254,
 1.9178124992054855,
 6.690936519667144,
 0.9207860492857542,
 10.49433643133247,
 6.852090467850956,
 2.209186213261008,
 8.40962131961535,
 10.035495568569523]